### ISSUE TITLE
Inline editing

### ISSUE THREAD

**Issue by lobosan** [aldeed/meteor-tabular#23]
Hi @aldeed. I was wondering if you could provide a reactive example for inline editing like this?

https://editor.datatables.net/examples/inline-editing/simple.html

Thanks in advance for your help

**Comment by jonlachlan** [comment]
Not sure about DataTable's Editor extension, but something comparable can be accomplished using x-editable. Add these two meteor packages: 
```meteor add natestrauser:x-editable-bootstrap```
```meteor add workman:x-editable-reactive-template```
The second table lets you use the blaze tag ```{{> xEditable}}```. I made a template called cellEditable:
```html
<template name="cellEditable">
{{> xEditable type="text" success=onSuccess mode="inline" onblur="ignore" showbuttons="bottom" placement="right" placeholder="Enter value..." value=cellValue data-emptytext="Click to add..."}}
</template>
```
In my js file:
```javascript
 Template.cellEditable.helpers({
    onSuccess: function () {
        var obj = this;
        var id = this._id;
        return function (res, val) {
        	obj[key] = val;
        	MyCollection.update({_id:id}, {$set:obj});
        }
	},
    cellValue: function (context, options) {
    	var key = Template.parentData(1).key;
    	var row = this;
    	return row[key];
    }
  });
```
The ```onSuccess``` function actually updates the entire object.  The reason I update the whole object is to take advantage of the autoValue possibilities in aldeed:collection2, which I need the entire object to accomplish. You could make the function edit only the value that was changed, which could be done with the following code:
```javascript
onSuccess: function () {
        var key = Template.parentData(1).key;  // Get key so that we can apply change to only the one field.
        var id = this._id;
        return function (res, val) {
         	var setModifier = { $set: {} };
        	setModifier.$set[key] = val;
        	MyCollection.update({_id:id}, setModifier);
        }
}
```
Either approach is valid.

Now you can create your DataTable using tabular and then reference Template.cellEditable in your table definition:
```html
<template name="myTabularTable">
  {{> reactiveTable settings=settings class="table table-bordered table-hover"}}
</template>
```
```javascript
Template.myTabularTable.helpers({
    settings: function () {
        return {
           collection:MyCollection,
            rowsPerPage: 50,
            fields: [
            { key: 'col1', label:'Column 1',tmpl:Template.cellEditable}
            ]
        };
    }
});
```
At this point you can use Template.cellEditable for any column in any table that you want to have reactive editing capabilities. However, the code would only work for a single collection, MyCollection. You could create multiple xEditable templates for each collection you have, or perhaps rework the code to pass in the name of the collection subscription as an argument

I also answered a similar question you posed for Handsontable: http://stackoverflow.com/questions/27701527/meteor-handsontable-example

**Comment by lobosan** [comment]
Thank you anyway for your previous answer. It would be nice if Tabular could work with Editor extension in a reactive way.

**Comment by jonlachlan** [comment]
I believe an upcoming update of Tabular will be truly reactive in that it will update the number of rows when data changes.

**Comment by aldeed** [comment]
1.0 is released and should fix this. Please see updated [README](https://github.com/aldeed/meteor-tabular/blob/master/README.md) for all features and options.

Is there anything you still need help with here?

**Comment by lobosan** [comment]
All good @aldeed. Thank you so much for your amazing contribution to the meteor community. You are a legend ;)

**Comment by dh1tw** [comment]
thanks for your work @aldeed!! Somehow it is still not clear to me how to initialize and use DataTables.Editor with meteor-tabular. I would very much appreciate a short example.
Thanks!

**Comment by prodogs** [comment]
Is there an example on how to use editable forms?

**Comment by Madsn** [comment]
+1 for some documentation or example on inline editing

**Comment by sgelbart** [comment]
+1 for example! @lobosan?

**Comment by chieina** [comment]
+1 for example. Thanks in advance.

**Comment by serkyen** [comment]
+1 for example. Thanks

**Comment by djclarkson** [comment]
+1 please!

**Comment by Amritpd** [comment]
+1 example

**Comment by omargohan** [comment]
+1 for example.

**Comment by promentol** [comment]
+1 for example

**Comment by CarlosMC** [comment]
+1 for example. Please.

**Comment by nacimgoura** [comment]
+1 example
